parameters:
#    cinemax_feedback.example.class: Cinemax\FeedbackBundle\Example

services:
#    cinemax_feedback.example:
#        class: %cinemax_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
