cinemax_videos:
    resource: "@CinemaxVideosBundle/Resources/config/routing.yml"
    prefix:   /

strokit_config:
    resource: "@StrokitConfigBundle/Resources/config/routing.yml"
    prefix:   /admin

cinemax_feedback:
    resource: "@CinemaxFeedbackBundle/Resources/config/routing.yml"
    prefix:   /

cinemax_homepage:
    resource: "@CinemaxBundle/Resources/config/routing.yml"
    prefix:   /

#article:
#    resource: "@ArticleBundle/Resources/config/routing.yml"
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
# app/config/routing.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: SonataUserBundle:Profile:show }
    requirements:
        _method: GET

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonataadmin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonataadmin

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /sonataadmin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

news:
    resource: '@ApplicationSonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb