parameters:
#    cinemax_header_slider.example.class: Cinemax\HeaderSliderBundle\Example

services:
#    cinemax_header_slider.example:
#        class: %cinemax_header_slider.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
