parameters:
#    cinemax_header.example.class: Cinemax\Header\HeaderBundle\Example

services:
#    cinemax_header.example:
#        class: %cinemax_header.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
