parameters:
#    cinemax_videos.example.class: Cinemax\VideosBundle\Example

services:
#    cinemax_videos.example:
#        class: %cinemax_videos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
