parameters:
#    cinemax.example.class: Cinemax\CinemaxBundle\Example

services:
#    cinemax.example:
#        class: %cinemax.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
